"""concinno.agent — Agent management subsystem facade.

Re-exports from top-level modules for ``from concinno.agent import …`` usage.
"""

from concinno.agent.asymmetry import (
    HARDCODED_AXES,
    NEW_NOVEL_AXES,
    AsymmetryPlan,
    EpistemicAxis,
    RolePlan,
)
from concinno.agent.commander import (
    COMPLEXITY_PRIOR,
    TIER_0_MAX_ALPHA,
    TIER_1_MAX_ALPHA,
    TIER_2_MAX_ALPHA,
    TIER_BUDGETS,
    Commander,
    TierBudget,
    TierDecision,
)
from concinno.agent.confidence_fusion import AlphaSignal
from concinno.agent.fork_context import (
    ANTHROPIC_MAX_CACHE_BREAKPOINTS,
    FORK_PLACEHOLDER_RESULT,
    CacheSafeParams,
    FileStateCache,
    ForkDepthExceeded,
    RenderedPromptCache,
    SubagentContext,
    create_cache_safe_params,
    create_subagent_context,
    estimate_cache_savings,
    insert_cache_breakpoints,
    is_in_fork_child,
    normalize_tool_result_for_cache,
    render_for_fork_byte_exact,
)
from concinno.agent.iterative_retrieve import (
    CascadeConfig,
    CascadeStats,
    EvolutionScheduler,
    IterativeRetriever,
    L1Retriever,
    RetrievalResult,
)
from concinno.agent.mas_loop import (
    MASConfig,
    MASResult,
    blind_label_order,
    derive_role_seeds,
    run_mas,
    truncate_trace_top_k,
)
from concinno.agent.mas_prompts import (
    DEFAULT_CRITIC_FALLBACK_PROMPT,
    DEFAULT_CRITIC_PROMPT,
    DEFAULT_JUDGE_PROMPT,
)
from concinno.agent.parallel_dispatch import (
    COORDINATOR_PROMPT_SNIPPET,
    DEFAULT_MAX_FORK_DEPTH,
    DEFAULT_MAX_PARALLEL,
    DispatchFeatures,
    DispatchPlan,
    DispatchRejected,
    ForkInForkRejected,
    ParallelDispatcher,
    ParallelLimitExceeded,
    SimpleFeatures,
    SpawnPath,
    SpawnRequest,
    TeammateCannotSpawnBackground,
    TeammateCannotSpawnTeammate,
)
from concinno.agent.prompts import (
    AGENT_GUIDANCE_ARITHMETIC,
    AGENT_GUIDANCE_COMPUTE_TOOLS,
    AGENT_GUIDANCE_EXACT_QUOTE,
    AGENT_GUIDANCE_EXACT_UNIT,
    AGENT_GUIDANCE_FACTUAL_COUNT,
    AGENT_GUIDANCE_NO_REFUSAL,
    AGENT_GUIDANCE_SEARCH_DISCIPLINE,
    AGENT_GUIDANCE_UNCERTAINTY,
    ANCHOR_PATTERNS,
    build_targeted_guidance,
    default_guidance,
    select_question_anchors,
)
from concinno.agent.retrieve_pipeline import (
    CascadePipelineResult,
    ZIQCascadePipeline,
)
from concinno.agent.sentinel_parser import extract_sentinel_answer
from concinno.agent_artifact_guard import AgentArtifactGuard
from concinno.agent_gate import (
    AgentGateGuard,
    check,
    gate_agent_cap,
    is_research_agent,
)
from concinno.agent_supervisor import (
    AgentSupervisor,
    SupervisedTask,
    VerificationResult,
    verify_task,
)

__all__ = [
    "AGENT_GUIDANCE_ARITHMETIC",
    "AGENT_GUIDANCE_COMPUTE_TOOLS",
    "AGENT_GUIDANCE_EXACT_QUOTE",
    "AGENT_GUIDANCE_EXACT_UNIT",
    "AGENT_GUIDANCE_FACTUAL_COUNT",
    "AGENT_GUIDANCE_NO_REFUSAL",
    "AGENT_GUIDANCE_SEARCH_DISCIPLINE",
    "AGENT_GUIDANCE_UNCERTAINTY",
    "ANCHOR_PATTERNS",
    "ANTHROPIC_MAX_CACHE_BREAKPOINTS",
    "COMPLEXITY_PRIOR",
    "COORDINATOR_PROMPT_SNIPPET",
    "DEFAULT_CRITIC_FALLBACK_PROMPT",
    "DEFAULT_CRITIC_PROMPT",
    "DEFAULT_JUDGE_PROMPT",
    "DEFAULT_MAX_FORK_DEPTH",
    "DEFAULT_MAX_PARALLEL",
    "FORK_PLACEHOLDER_RESULT",
    "HARDCODED_AXES",
    "NEW_NOVEL_AXES",
    "TIER_0_MAX_ALPHA",
    "TIER_1_MAX_ALPHA",
    "TIER_2_MAX_ALPHA",
    "TIER_BUDGETS",
    "AgentArtifactGuard",
    "AgentGateGuard",
    "AgentSupervisor",
    "AlphaSignal",
    "AsymmetryPlan",
    "CacheSafeParams",
    "CascadeConfig",
    "CascadePipelineResult",
    "CascadeStats",
    "Commander",
    "DispatchFeatures",
    "DispatchPlan",
    "DispatchRejected",
    "EpistemicAxis",
    "EvolutionScheduler",
    "FileStateCache",
    "ForkDepthExceeded",
    "ForkInForkRejected",
    "IterativeRetriever",
    "L1Retriever",
    "MASConfig",
    "MASResult",
    "ParallelDispatcher",
    "ParallelLimitExceeded",
    "RenderedPromptCache",
    "RetrievalResult",
    "RolePlan",
    "SimpleFeatures",
    "SpawnPath",
    "SpawnRequest",
    "SubagentContext",
    "SupervisedTask",
    "TeammateCannotSpawnBackground",
    "TeammateCannotSpawnTeammate",
    "TierBudget",
    "TierDecision",
    "VerificationResult",
    "ZIQCascadePipeline",
    "blind_label_order",
    "build_targeted_guidance",
    "check",
    "create_cache_safe_params",
    "create_subagent_context",
    "default_guidance",
    "derive_role_seeds",
    "estimate_cache_savings",
    "extract_sentinel_answer",
    "gate_agent_cap",
    "insert_cache_breakpoints",
    "is_in_fork_child",
    "is_research_agent",
    "normalize_tool_result_for_cache",
    "render_for_fork_byte_exact",
    "run_mas",
    "select_question_anchors",
    "truncate_trace_top_k",
    "verify_task",
]
