"""concinno security primitives — 9-layer defense-in-depth stack.

Re-exports permission-mode FSM, bash validators, SSRF guard,
LLM-judge prompt-injection detector, and policy-as-code engine.
"""

from concinno.security.bash_validators import (  # noqa: F401
    DEFAULT_VALIDATOR_CHAIN,
    BashValidator,
    BashValidatorConfig,
    ValidationResult,
    split_compound_command,
    strip_safe_wrappers,
    validate_backslash_escaped_operators,
    validate_backslash_escaped_whitespace,
    validate_brace_expansion,
    validate_carriage_return,
    validate_comment_quote_desync,
    validate_dangerous_patterns,
    validate_dangerous_variables,
    validate_empty,
    validate_git_commit,
    validate_ifs_injection,
    validate_incomplete_commands,
    validate_jq_command,
    validate_length,
    validate_malformed_token_injection,
    validate_mid_word_hash,
    validate_newlines,
    validate_obfuscated_flags,
    validate_proc_environ_access,
    validate_quoted_newline,
    validate_redirections,
    validate_safe_command_substitution,
    validate_shell_metacharacters,
    validate_unicode_whitespace,
    validate_zsh_dangerous_commands,
)
from concinno.security.circuit_breaker_guard import (  # noqa: F401
    DEFAULT_BACKOFF_BASE_S,
    DEFAULT_BACKOFF_MAX_S,
    DEFAULT_COOLDOWN_S,
    DEFAULT_FAILURE_THRESHOLD,
    DEFAULT_MAX_CALLS,
    DEFAULT_WINDOW_S,
    CallRecord,
    CircuitBreakerFinding,
    CircuitBreakerGuard,
    CircuitBreakerSnapshot,
    CircuitState,
)
from concinno.security.deserialize_guard import (  # noqa: F401
    DEFAULT_TRUSTED_MODULES,
    PATTERN_SEVERITY,
    SAFE_YAML_FUNCTIONS,
    SAFE_YAML_LOADERS,
    DeserializeFinding,
    DeserializeGuard,
)
from concinno.security.http_client_guard import (  # noqa: F401
    DEFAULT_ALLOWLIST,
    DEFAULT_DENYLIST,
    PRODUCTION_HOST_PATTERNS,
    SECRET_HEADER_PATTERNS,
    HttpClientFinding,
    HttpClientGuard,
    HttpClientPipelineGuard,
    HttpRequestPayload,
    extract_payload,
    parse_curl_command,
    parse_python_http_kwargs,
)
from concinno.security.llm_judge_guard import (  # noqa: F401
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_MAX_CACHE_SIZE,
    InjectionJudge,
    InjectionVerdict,
    JudgeRequest,
    LLMJudgeGuard,
    LLMJudgeStats,
)
from concinno.security.permission_mode import (  # noqa: F401
    AUTO_SAFE_TOOLS,
    EXEC_TOOLS,
    READ_ONLY_TOOLS,
    WRITE_TOOLS,
    PermissionHook,
    PermissionMode,
    PermissionModeFSM,
    PermissionRequest,
    PermissionRule,
    PermissionVerdict,
)
from concinno.security.pii_guard import (  # noqa: F401
    PIIGuard,
    PIIType,
)
from concinno.security.policy_gate import (  # noqa: F401
    OWASP_LLM_BASELINE,
    CallableMatcher,
    CompositeMatcher,
    ContentPatternMatcher,
    Decision,
    EngineResult,
    FailMode,
    Finding,
    MetadataMatcher,
    PolicyAction,
    PolicyContext,
    PolicyEngine,
    PolicyGate,
    PolicyGateResult,
    PolicyMatcher,
    PolicyRule,
    PolicyVerdict,
    Severity,
    ThreatCategory,
    ToolNameMatcher,
)
from concinno.security.rce_injection_guard import (  # noqa: F401
    RCE_PATTERN_SEVERITY,
    RceFinding,
    RceInjectionBaseGuard,
    RceInjectionGuard,
    RcePayload,
    extract_code_payload,
)
from concinno.security.sql_injection_guard import (  # noqa: F401
    SqlInjectionFinding,
    SqlInjectionGuard,
    extract_sql_payload,
)
from concinno.security.ssrf_guard import (  # noqa: F401
    CLOUD_METADATA_HOSTS,
    CLOUD_METADATA_IPS,
    DEFAULT_ALLOWED_SCHEMES,
    DEFAULT_MAX_REDIRECTS,
    BlockReason,
    DNSResolver,
    SSRFCheckConfig,
    SSRFGuard,
    SSRFVerdict,
    canonicalize_host,
    is_private_ip,
)

__all__ = [
    "AUTO_SAFE_TOOLS",
    "BashValidator",
    "BlockReason",
    "CLOUD_METADATA_HOSTS",
    "CLOUD_METADATA_IPS",
    "DEFAULT_ALLOWED_SCHEMES",
    "DEFAULT_MAX_REDIRECTS",
    "DNSResolver",
    "SSRFCheckConfig",
    "SSRFGuard",
    "SSRFVerdict",
    "canonicalize_host",
    "is_private_ip",
    "BashValidatorConfig",
    "DEFAULT_VALIDATOR_CHAIN",
    "EXEC_TOOLS",
    "PermissionHook",
    "PermissionMode",
    "PermissionModeFSM",
    "PermissionRequest",
    "PermissionRule",
    "PermissionVerdict",
    "READ_ONLY_TOOLS",
    "ValidationResult",
    "WRITE_TOOLS",
    "split_compound_command",
    "strip_safe_wrappers",
    "validate_backslash_escaped_operators",
    "validate_backslash_escaped_whitespace",
    "validate_brace_expansion",
    "validate_carriage_return",
    "validate_comment_quote_desync",
    "validate_dangerous_patterns",
    "validate_dangerous_variables",
    "validate_empty",
    "validate_git_commit",
    "validate_ifs_injection",
    "validate_incomplete_commands",
    "validate_jq_command",
    "validate_length",
    "validate_malformed_token_injection",
    "validate_mid_word_hash",
    "validate_newlines",
    "validate_obfuscated_flags",
    "validate_proc_environ_access",
    "validate_quoted_newline",
    "validate_redirections",
    "validate_safe_command_substitution",
    "validate_shell_metacharacters",
    "validate_unicode_whitespace",
    "validate_zsh_dangerous_commands",
    # L8 LLM-judge prompt injection detector
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DEFAULT_MAX_CACHE_SIZE",
    "InjectionJudge",
    "InjectionVerdict",
    "JudgeRequest",
    "LLMJudgeGuard",
    "LLMJudgeStats",
    # L9 Policy-as-code engine
    "CallableMatcher",
    "CompositeMatcher",
    "ContentPatternMatcher",
    "EngineResult",
    "MetadataMatcher",
    "OWASP_LLM_BASELINE",
    "PolicyAction",
    "PolicyContext",
    "PolicyEngine",
    "PolicyMatcher",
    "PolicyRule",
    "PolicyVerdict",
    "ThreatCategory",
    "ToolNameMatcher",
    # 4.3.0 — PolicyGate shared base for security guards
    "Decision",
    "FailMode",
    "Finding",
    "PolicyGate",
    "PolicyGateResult",
    "Severity",
    # 4.3.0 — Deserialize guard
    "DEFAULT_TRUSTED_MODULES",
    "DeserializeFinding",
    "DeserializeGuard",
    "PATTERN_SEVERITY",
    "SAFE_YAML_FUNCTIONS",
    "SAFE_YAML_LOADERS",
    # 4.3.0 — PII guard
    "PIIGuard",
    "PIIType",
    # 4.4.0 — Circuit breaker guard
    "CallRecord",
    "CircuitBreakerFinding",
    "CircuitBreakerGuard",
    "CircuitBreakerSnapshot",
    "CircuitState",
    "DEFAULT_BACKOFF_BASE_S",
    "DEFAULT_BACKOFF_MAX_S",
    "DEFAULT_COOLDOWN_S",
    "DEFAULT_FAILURE_THRESHOLD",
    "DEFAULT_MAX_CALLS",
    "DEFAULT_WINDOW_S",
    # 4.6.0 — RCE injection guard
    "RCE_PATTERN_SEVERITY",
    "RceFinding",
    "RceInjectionBaseGuard",
    "RceInjectionGuard",
    "RcePayload",
    "extract_code_payload",
    # 4.6.0 — SQL injection guard
    "SqlInjectionFinding",
    "SqlInjectionGuard",
    "extract_sql_payload",
    # 4.6.0 — HTTP-client request-shape policy gate
    "DEFAULT_ALLOWLIST",
    "DEFAULT_DENYLIST",
    "HttpClientFinding",
    "HttpClientGuard",
    "HttpClientPipelineGuard",
    "HttpRequestPayload",
    "PRODUCTION_HOST_PATTERNS",
    "SECRET_HEADER_PATTERNS",
    "extract_payload",
    "parse_curl_command",
    "parse_python_http_kwargs",
]
