"""cc_cortex.agent — Agent management subsystem facade.

Re-exports from top-level modules for ``from cc_cortex.agent import …`` usage.
"""

from cc_cortex.agent.fork_context import (
    ANTHROPIC_MAX_CACHE_BREAKPOINTS,
    FORK_PLACEHOLDER_RESULT,
    CacheSafeParams,
    FileStateCache,
    ForkDepthExceeded,
    RenderedPromptCache,
    SubagentContext,
    create_cache_safe_params,
    create_subagent_context,
    estimate_cache_savings,
    insert_cache_breakpoints,
    is_in_fork_child,
    normalize_tool_result_for_cache,
    render_for_fork_byte_exact,
)
from cc_cortex.agent.iterative_retrieve import (
    CascadeConfig,
    CascadeStats,
    EvolutionScheduler,
    IterativeRetriever,
    L1Retriever,
    RetrievalResult,
)
from cc_cortex.agent.parallel_dispatch import (
    COORDINATOR_PROMPT_SNIPPET,
    DEFAULT_MAX_FORK_DEPTH,
    DEFAULT_MAX_PARALLEL,
    DispatchFeatures,
    DispatchPlan,
    DispatchRejected,
    ForkInForkRejected,
    ParallelDispatcher,
    ParallelLimitExceeded,
    SimpleFeatures,
    SpawnPath,
    SpawnRequest,
    TeammateCannotSpawnBackground,
    TeammateCannotSpawnTeammate,
)
from cc_cortex.agent.retrieve_pipeline import (
    CascadePipelineResult,
    ZIQCascadePipeline,
)
from cc_cortex.agent_artifact_guard import AgentArtifactGuard
from cc_cortex.agent_gate import (
    AgentGateGuard,
    check,
    gate_agent_cap,
    is_research_agent,
)
from cc_cortex.agent_supervisor import (
    AgentSupervisor,
    SupervisedTask,
    VerificationResult,
    verify_task,
)

__all__ = [
    "ANTHROPIC_MAX_CACHE_BREAKPOINTS",
    "COORDINATOR_PROMPT_SNIPPET",
    "DEFAULT_MAX_FORK_DEPTH",
    "DEFAULT_MAX_PARALLEL",
    "FORK_PLACEHOLDER_RESULT",
    "AgentArtifactGuard",
    "AgentGateGuard",
    "AgentSupervisor",
    "CacheSafeParams",
    "CascadeConfig",
    "CascadePipelineResult",
    "CascadeStats",
    "DispatchFeatures",
    "DispatchPlan",
    "DispatchRejected",
    "EvolutionScheduler",
    "FileStateCache",
    "ForkDepthExceeded",
    "ForkInForkRejected",
    "IterativeRetriever",
    "L1Retriever",
    "ParallelDispatcher",
    "ParallelLimitExceeded",
    "RenderedPromptCache",
    "RetrievalResult",
    "SimpleFeatures",
    "SpawnPath",
    "SpawnRequest",
    "SubagentContext",
    "SupervisedTask",
    "TeammateCannotSpawnBackground",
    "TeammateCannotSpawnTeammate",
    "VerificationResult",
    "ZIQCascadePipeline",
    "check",
    "create_cache_safe_params",
    "create_subagent_context",
    "estimate_cache_savings",
    "gate_agent_cap",
    "insert_cache_breakpoints",
    "is_in_fork_child",
    "is_research_agent",
    "normalize_tool_result_for_cache",
    "render_for_fork_byte_exact",
    "verify_task",
]
